### PR TITLE
Add grid and table functions which return CMIs

### PR DESCRIPTION
**Pull request by Xitian9**
Occasionally, the ColModInfo used to generate a table is needed externally. This allows you to get that without copying over all the code manually.

### CODE REVIEW

**Comment by muesli4** [comment]
When would that be the case?  (Background:  I was trying to move definitions with more complexity into sub-modules.)

**Comment by Xitian9** [comment]
In the `hledger` package we render some tables, and then later on need to make a line with the same width as some of the columns. If you'd prefer the complexity to be in submodules, I can change the definition of `deriveColMods` instead. But I don't think unwrapping this one level of wrappers significantly increases code complexity (`zipWith ($)` is not particularly simpler than `zipWith4`).

**Comment by muesli4** [comment]
I think it is fine.  I am trying to keep the types opaque for the users in case they have to be changed later on.

**Comment by muesli4** [comment]
> This allows you to get that without copying over all the code manually.

* Instead of _allow_ use _enable_.  It is not a matter of permission.
* I would not address the reader directly.  Either use, for example, _the user_ or turn the verb into a gerund.

**Comment by Xitian9** [comment]
Updated.

**Pull request merged**
