### PR TITLE
Allow base<=4.14

### PR DESCRIPTION
**Pull request by thestr4ng3r**
It works fine for me with that version, including the tests.

### CODE REVIEW

**Comment by muesli4** [comment]
It may work now. But since version 4.13 is not released yet it might break something in the future. What's your motivation?

**Comment by ehamberg** [comment]
base 4.13 is shipped with GHC 8.8 that was released in August 2019 and is used in the newest LTS snapshot (LTS-15) of Stackage.

**Comment by lierdakil** [comment]
@muesli4 could you perhaps relax the constraints on Hackage? https://hackage.haskell.org/package/table-layout still says base (>=4.8 && <4.13)

P.S. also, while at it, probably a good idea to raise the lower bound to 4.9, since the package fails to build with GHC 7.10: https://matrix.hackage.haskell.org/#/package/table-layout/0.8.0.5/ghc-7.10.3@1584142811

**Comment by muesli4** [comment]
@lierdakil I'm sorry, I didn't release a new version. I will try to get it released this weekend.

> P.S. also, while at it, probably a good idea to raise the lower bound to 4.9, since the package fails to build with GHC 7.10: https://matrix.hackage.haskell.org/#/package/table-layout/0.8.0.5 ghc-7.10.3@1584142811

Then I first have to make sure it works.

**Comment by lierdakil** [comment]
Fwiw, you don't have to release a new version. You can just tweak version constraints by editing metadata on Hackage.

**Pull request merged**
